n = int(input('Qual tabuada você quer saber? '))
print('\033[1;34m 1 x {:2} = {}\n'.format(n, n * 1),
      '2 x {:2} = {}\n'.format(n, n * 2),
      '3 x {:2} = {}\n'.format(n, n * 3),
      '4 x {:2} = {}\n'.format(n, n * 4),
      '5 x {:2} = {}\n'.format(n, n * 5),
      '6 x {:2} = {}\n'.format(n, n * 6),
      '7 x {:2} = {}\n'.format(n, n * 7),
      '8 x {:2} = {}\n'.format(n, n * 8),
      '9 x {:2} = {}\n'.format(n, n * 9),
      '10 x {} = {}\033[1;4m\n'.format(n, n * 10))
